- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt:
      pkg:
        - neovim
        - tmux
  - name: Add VS Code GPG apt key
    apt_key: 
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
  - name: Update cache
    apt:
      update_cache: yes
  - name: Installing VS Code
    apt:
      pkg:
        - apt-transport-https
        - code
