- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt:
      pkg:
        - neovim
        - tmux
  - name: Add VS Code apt repo & signing key
    command: sh scripts/vscode.sh
  - name: Installing VS Code
    apt:
      pkg:
        - apt-transport-https
        - code
